// ─────────────────────────────────────────────────────────────────────────────
// Gmail over SMTP with a Google App Password (ADR 0010).
//
// WHY SMTP AND NOT THE GMAIL API. The org's community address is a consumer
// `@gmail.com` account (2026-09-06). The Gmail API needs `gmail.send`, a RESTRICTED
// scope: an unverified OAuth app is blocked on it, and a "Testing" consent screen
// issues refresh tokens that die after seven days — the same trap ARCHITECTURE.md §4.1
// records for Drive. An App Password has neither problem: 2-Step Verification on the
// account, one 16-character secret, SMTP over TLS. It is generated by the account
// holder, placed in Vercel and Bitwarden by the CTO, and never pasted anywhere else.
//
// LIMITS (documented, not hidden — runbook 03 row 11): roughly 500 recipients per day
// from a consumer account, bulk sends risk spam classification, and there are NO
// bounce webhooks — delivery status is sent/failed only, and bounces land in the inbox.
// A real launch wants Workspace, or Resend once the org owns a domain (PRD OQ-10).
// Either is `MAIL_TRANSPORT=` away.
//
// PRIVACY: nodemailer's `logger`/`debug` stay OFF — with them on, every recipient and
// body would be written to the function logs (RA 10173). Errors are mapped to a reason
// and a short message; the recipient never appears in either.
// ─────────────────────────────────────────────────────────────────────────────

import nodemailer, { type Transporter } from "nodemailer";

import {
  isPlausibleAddress,
  type MailFailureReason,
  type MailMessage,
  type MailResult,
  type MailTransport,
} from "./types";

export type GmailSmtpConfig = {
  user: string;
  appPassword: string;
  fromName: string;
  replyTo: string | null;
};

/** Read the five `GMAIL_*` / `MAIL_*` variables. Throws on a missing credential — a misconfigured transport must fail at boot, not on the 400th recipient. */
export function readGmailSmtpConfig(
  env: Readonly<Record<string, string | undefined>>,
): GmailSmtpConfig {
  const user = (env.GMAIL_SMTP_USER ?? "").trim();
  const appPassword = (env.GMAIL_SMTP_APP_PASSWORD ?? "").replace(/\s+/g, "");
  if (user === "" || appPassword === "") {
    throw new Error(
      "MAIL_TRANSPORT=gmail_smtp needs GMAIL_SMTP_USER and GMAIL_SMTP_APP_PASSWORD. " +
        "See .env.example and docs/runbooks/03-CREDENTIAL_ROTATION.md row 11.",
    );
  }
  return {
    user,
    appPassword,
    fromName: (env.MAIL_FROM_NAME ?? "").trim() || "START-DOST",
    replyTo: (env.MAIL_REPLY_TO ?? "").trim() || null,
  };
}

/** Google's SMTP error surface, mapped to the caller's four reasons. */
export function classifySmtpError(error: unknown): { reason: MailFailureReason; message: string } {
  const e = error as { code?: string; responseCode?: number; response?: string; message?: string };
  const code = e?.responseCode ?? 0;
  const text = String(e?.response ?? e?.message ?? "smtp error");
  if (e?.code === "EAUTH" || code === 535) {
    return { reason: "misconfigured", message: "smtp authentication failed" };
  }
  // 421 / 450 / 451 / 452 are Gmail's "try again later" family, including the daily cap.
  if (code === 421 || (code >= 450 && code <= 452) || /quota|limit|rate/i.test(text)) {
    return { reason: "throttled", message: `smtp deferred (${code || "4xx"})` };
  }
  if (code >= 500 && code < 600) {
    return { reason: "rejected", message: `smtp rejected (${code})` };
  }
  return { reason: "unavailable", message: "smtp unreachable" };
}

export function createGmailSmtpTransport(
  config: GmailSmtpConfig,
  transporter?: Transporter,
): MailTransport {
  const smtp =
    transporter ??
    nodemailer.createTransport({
      host: "smtp.gmail.com",
      port: 465,
      secure: true,
      auth: { user: config.user, pass: config.appPassword },
      // A campaign chunk is 100 messages; one pooled connection keeps Gmail from
      // treating each message as a new login.
      pool: true,
      maxConnections: 1,
      maxMessages: 100,
      logger: false,
      debug: false,
    });

  const from = `"${config.fromName.replace(/"/g, "")}" <${config.user}>`;

  return {
    name: "gmail_smtp",

    async send(message: MailMessage): Promise<MailResult> {
      if (!isPlausibleAddress(message.to)) {
        return { ok: false, reason: "rejected", message: "recipient address is not deliverable" };
      }
      try {
        const info = await smtp.sendMail({
          from,
          to: message.to,
          subject: message.subject,
          html: message.html,
          text: message.text,
          replyTo: message.replyTo ?? config.replyTo ?? undefined,
        });
        return { ok: true, providerMessageId: info.messageId ?? null };
      } catch (error) {
        return { ok: false, ...classifySmtpError(error) };
      }
    },

    async ping() {
      try {
        await smtp.verify();
        return { ok: true, detail: `gmail_smtp as ${config.user}` };
      } catch (error) {
        return { ok: false, detail: classifySmtpError(error).message };
      }
    },
  };
}
