// ─────────────────────────────────────────────────────────────────────────────
// Zero-filling (BUILD_PLAN S6-T6).
//
// The views in 0032 cannot invent a row for a status nobody holds or a region with no
// members — a `group by` has nothing to group. Left as-is, a brand-new term renders an
// EMPTY panel, which reads as "the dashboard is broken" on precisely the morning it is
// most likely to be looked at: the day after rollover, when the correct answer is a
// screen full of honest zeros (PRD US-H2 — "dashboards wiped clean" is true of the view,
// never of the data).
//
// ═══════════════════════════════════════════════════════════════════════════════
// TWO RULES, BOTH OF WHICH ARE ABOUT NOT HAND-TYPING A LIST
// ═══════════════════════════════════════════════════════════════════════════════
//
// 1. STATUSES COME FROM THE GENERATED ENUM. `Constants.public.Enums.membership_status`
//    is regenerated by `pnpm db:types` from the migrations. A hand-typed literal array
//    silently drops a status from every dashboard the moment the enum grows — the tile
//    would simply stop appearing, with no error anywhere. `terminated` (CBL Art. VII §3)
//    is exactly the kind of member that arrives by amendment.
//
// 2. THE LABEL MAP IS A `Record` OVER THE UNION, SO A NEW MEMBER IS A COMPILE ERROR.
//    That is the whole reason it is a `Record` and not a lookup with a fallback: a
//    fallback would render `renewal_pending` verbatim on an admin dashboard and nobody
//    would notice for a term. Failing the build is the cheaper outcome.
//
// Regions are zero-filled against rows read from the `regions` TABLE for the same reason
// — RA 12000 (2024) made it 18 by carving out the Negros Island Region, and a hard-coded
// list is how the 19th goes missing (DATA_MODEL.md §6/0016).
//
// PURE FUNCTIONS ONLY. Nothing here fetches, and nothing here is server-only: the
// components render what these return.
//
// CITATION: BUILD_PLAN S6-T6, S6-T9, S6-T12; ADR 0007; PRD US-D4, US-F1, US-H2;
//           CBL Art. III §5 (committees are per-term and discretionary).
// ─────────────────────────────────────────────────────────────────────────────

import { Constants } from "@/database.types";
import type {
  CommitteeBucket,
  CommitteeCountRow,
  MembershipStatus,
  RegionBucket,
  RegionCountRow,
  RegionRef,
  StatusBucket,
  StatusCountRow,
} from "@/lib/dashboard/types";

/**
 * The membership statuses, in the order the enum declares them — which is the lifecycle
 * order (`renewal_pending` → `active` → the four exits), so the tiles read left to right
 * the way the state machine runs (DATA_MODEL.md §3.1).
 */
export const MEMBERSHIP_STATUS_ORDER: readonly MembershipStatus[] =
  Constants.public.Enums.membership_status;

/**
 * Human labels, keyed by the generated union.
 *
 * ⚠ ADDING A MEMBER TO `membership_status` IS A TYPE ERROR HERE. That is deliberate and
 * is the point of the `Record` — see rule 2 in the header.
 */
export const MEMBERSHIP_STATUS_LABELS: Record<MembershipStatus, string> = {
  renewal_pending: "Renewal pending",
  active: "Active",
  graduated: "Graduated",
  resigned: "Resigned",
  left: "Left",
  // CBL Art. VII §3 — removal from the organization by a majority vote of the Executive
  // Board. Labelled distinctly from "Left" on purpose: an adjudicated removal and an
  // unreturned renewal form must never read the same on a dashboard.
  terminated: "Terminated",
};

/** The label for a status. Total by construction; no fallback exists or is wanted. */
export function membershipStatusLabel(status: MembershipStatus): string {
  return MEMBERSHIP_STATUS_LABELS[status];
}

/**
 * Every status, in enum order, at 0 where the view returned nothing (PRD US-D4).
 *
 * Rows for a status not in the enum are ignored rather than rendered — the only way one
 * can occur is a database ahead of `database.types.ts`, and inventing a tile with no
 * label for it would be worse than omitting it until types are regenerated.
 */
export function zeroFillStatuses(rows: readonly StatusCountRow[]): StatusBucket[] {
  const counts = new Map<MembershipStatus, number>();
  for (const row of rows) {
    counts.set(row.status, (counts.get(row.status) ?? 0) + row.member_count);
  }

  return MEMBERSHIP_STATUS_ORDER.map((status) => ({
    status,
    label: MEMBERSHIP_STATUS_LABELS[status],
    count: counts.get(status) ?? 0,
  }));
}

/** The term's total headcount — the sum of the status buckets, which DOES reconcile. */
export function totalFromStatuses(buckets: readonly StatusBucket[]): number {
  return buckets.reduce((sum, bucket) => sum + bucket.count, 0);
}

/**
 * Every region the caller can see, in `sort_order`, at 0 where it has no members.
 *
 * ⚠ THE `regions` ARGUMENT IS THE ZERO-FILL SET, AND IT IS NOT A SCOPE DECISION. On the
 * admin dashboard it is all 18; on the Regional Representative dashboard the caller
 * passes only the rep's own region(s), because filling 18 rows of zeros for a rep who
 * can see one region would imply they are looking at an org-wide panel that happens to
 * be empty. Either way the COUNTS come from the `security_invoker` view, so this
 * function cannot widen or narrow what anyone sees — it only decides which labels get a
 * bar (ADR 0007).
 *
 * A count for a region absent from `regions` is dropped: it cannot be labelled or
 * linked, and it can only mean the reference read failed.
 */
export function zeroFillRegions(
  regions: readonly RegionRef[],
  rows: readonly RegionCountRow[],
): RegionBucket[] {
  const counts = new Map<string, number>();
  for (const row of rows) {
    counts.set(row.region_id, (counts.get(row.region_id) ?? 0) + row.member_count);
  }

  return [...regions]
    .sort((a, b) => a.sort_order - b.sort_order)
    .map((region) => ({
      region_id: region.id,
      region_code: region.code,
      region_name: region.name,
      island_group: region.island_group,
      sort_order: region.sort_order,
      count: counts.get(region.id) ?? 0,
    }));
}

/** What the unassigned committee bucket is called on screen. */
export const UNASSIGNED_COMMITTEE_LABEL = "No committee";

/**
 * Committee bars, unassigned bucket last (PRD US-D4).
 *
 * ⚠ COMMITTEES ARE **NOT** ZERO-FILLED FROM A REFERENCE LIST HERE, and that asymmetry
 * against regions is the Constitution's rather than ours. CBL Art. III §5 makes
 * committees discretionary and per-term; there is no fixed set to fill against, and the
 * committee list a term happens to have is itself the answer. The officer committees
 * page (S6-T11) DOES render a zero for a committee with no members — it reads the
 * `committees` table directly for exactly that reason, because a committee created this
 * morning must be visible this afternoon.
 *
 * ⚠ THESE BARS DO NOT SUM TO THE HEADCOUNT. A member on two committees is counted under
 * each (CBL Art. III §5 sets no limit). Caption the panel; never reconcile it by picking
 * one committee per member (ADR 0007 §4).
 */
export function toCommitteeBuckets(rows: readonly CommitteeCountRow[]): CommitteeBucket[] {
  return rows.map((row) => ({
    committee_id: row.committee_id,
    committee_name: row.committee_name ?? UNASSIGNED_COMMITTEE_LABEL,
    count: row.member_count,
  }));
}
