-- ═══════════════════════════════════════════════════════════════════════════════════
-- 0065_disable_second_factor_temporarily.sql
--
-- WHAT:      TEMPORARY. Neutralises the database half of the 2FA gate by making
--            public.has_aal2() return true for every session. Every privileged write
--            policy and helper that gates on it — the inline aal2 predicate lives ONLY in
--            has_aal2() (0014:119), and is_user_roles_writer() (0014) plus the write
--            policies on user_roles, terms, application_windows, rr_region_grants and
--            privacy_notice_versions all call has_aal2() rather than inlining it — therefore
--            stops requiring a satisfied second factor. Nothing else changes.
--
-- WHY:       Project-head decision 2026-09-11 (Ethan): turn 2FA off for now, re-implement
--            soon. The middleware gate is turned off in parallel by DEV_DISABLE_MFA=1
--            (route-access.ts mfaGateEnabled()). Middleware alone is not enough — has_aal2()
--            guards WRITES at the data layer, so an aal1 session gets HTTP 200 + 0 rows on
--            role assignment, opening the application window and term rollover (the exact
--            silent breakage commit d44cffa documented). This migration is what makes the
--            app actually work while 2FA is off.
--
-- SCOPE:     has_aal2() is loosened, never tightened, so this can only PERMIT writes that
--            were already permitted by role. No policy, GRANT, or role boundary moves. The
--            RESTRICTIVE aal2 write policies and the definer-wrapper backstop from the
--            parked 0064 migration are deliberately NOT applied.
--
-- RE-ENABLE: revert with a later migration that restores the 0014 body verbatim:
--              create or replace function public.has_aal2() returns boolean
--              language sql stable set search_path = '' as $$
--                select (select auth.jwt() ->> 'aal') = 'aal2';
--              $$;
--            then re-home supabase/_parked/0064_second_factor_backstop.sql (renumbered to
--            follow the re-enable migration) and re-add DEV_DISABLE_MFA removal on Vercel.
--
-- ROLLBACK:  forward-only. Do not edit this file; write the re-enable migration above.
--
-- PRD:       US-A3, US-A4 (temporarily relaxed). Registered as launch debt.
-- ═══════════════════════════════════════════════════════════════════════════════════

create or replace function public.has_aal2() returns boolean
language sql
stable
set search_path = ''
as $$
  -- TEMPORARY: 2FA disabled org-wide (0065). Was:
  --   select (select auth.jwt() ->> 'aal') = 'aal2';
  select true;
$$;

comment on function public.has_aal2() is
  'TEMPORARILY forced true (migration 0065) — 2FA is disabled org-wide by project-head '
  'decision 2026-09-11, to be re-implemented. Original: true only for an aal2 session. '
  'Re-enable by restoring the aal2 jwt check and applying the parked 0064 backstop.';
